### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [zonetrooper32/AgeEstimateAdience#2]
Can you please share the model you converted from caffe to tensorflow?

**Comment by cjiang2** [comment]
Here we go: https://1drv.ms/u/s!AlPXmYPNRMsubRK-Eu78wn_3OXA
It should be noted that those weights are directly converted from pre-trained VGG Face Caffe model. (link: http://www.robots.ox.ac.uk/~vgg/software/vgg_face/)

**Comment by Zumbalamambo** [comment]
thank you so much.,. you saved my life... :)

**Comment by Zumbalamambo** [comment]
May i know how do i use this realtime? it will be a great help

**Comment by cjiang2** [comment]
As I mentioned before, the idea of real-time prediction is simple: load back the pre-trained model on audience dataset, and feed the image into the model to get a corresponding prediction. I suggest you to see this example and understand how it works. (https://www.cs.toronto.edu/~frossard/post/vgg16/)

Also, as for real-time, which is relevant to camera prediction. Basically you can understand a camera input as a "feed of images".  See the OpenCV official document for how it's done. (http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html)

Sorry for the late reply. I hope this can help!
